from dotenv import load_dotenv
from os import getenv

load_dotenv(override=True)

# LINKEDIN_ACCEESS_TOKEN = getenv('LINKEDIN_ACCEESS_TOKEN')
# LINKEDIN_ACCEESS_TOKEN_EXP = getenv('LINKEDIN_ACCEESS_TOKEN_EXP')

# HEADLESS = getenv('HEADLESS')

LINKEDIN_ACCEESS_TOKEN = "AQEDAUtZKmQFsQQyAAABl_MfXCQAAAGYFyvgJFYApRrvkCZNtyn9h_vi1Qt0ijiDvkA70PyVbDDQfSl3pkYeYTYEw3bd3zVnSnEOtaHPEbx5s9NOhdeLfgFbie3zoMKd7UZslStscRTrGy0K2qrv7EGo"
LINKEDIN_ACCEESS_TOKEN_EXP ="1783666608.0"
HEADLESS = "False"